name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: "github-bot"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        name: Cache Gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/build.gradle.kts') }}-${{ hashFiles('buildSrc/src/**') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/build.gradle.kts') }}
            ${{ runner.os }}-gradle-
      - name: Grant permission
        run: chmod +x gradlew
      - run: ./gradlew assemble
  librarian:
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_USER: "github-bot"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        name: Cache Gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/build.gradle.kts') }}-${{ hashFiles('buildSrc/src/**') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/build.gradle.kts') }}
            ${{ runner.os }}-gradle-
      - name: Grant permission
        run: chmod +x gradlew
      - ./gradlew librarianGenerateArtifacts
      - ./gradlew librarianGeneratePresetGroups
      - ./gradlew librarianGenerateGroups
      - ./gradlew librarianGeneratePages
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "update library notices"
          title: "update library notices"
          labels: "dependencies"
          assignees: "MeilCli"
          reviewers: "MeilCli"
          branch-suffix: "short-commit-hash"
