name: Release

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: "github-bot"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_TOKEN: ${{ secrets.BINTRAY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant permission
        run: chmod +x gradlew
      - run: echo "gpr.version=$tag" > buildSrc/version.properties
        env:
          tag: ${{ github.event.release.tag_name }}
      - run: ./gradlew :plugin-core:publishPluginMavenPublicationToGitHubPackagesRepository
      - run: ./gradlew :plugin-preset:publishPluginMavenPublicationToGitHubPackagesRepository
      - run: ./gradlew :ui-core:publishGprPublicationToGitHubPackagesRepository
      - run: ./gradlew :ui-activity:publishGprPublicationToGitHubPackagesRepository
      - run: ./gradlew :ui-fragment:publishGprPublicationToGitHubPackagesRepository
      - run: ./gradlew :ui-serializer-kotlin:publishGprPublicationToGitHubPackagesRepository
      - run: ./gradlew :ui-serializer-moshi:publishGprPublicationToGitHubPackagesRepository
      - run: ./gradlew :plugin-core:bintrayUpload
      - run: ./gradlew :plugin-preset:bintrayUpload
      - run: ./gradlew :ui-core:bintrayUpload
      - run: ./gradlew :ui-activity:bintrayUpload
      - run: ./gradlew :ui-fragment:bintrayUpload
      - run: ./gradlew :ui-serializer-kotlin:bintrayUpload
      - run: ./gradlew :ui-serializer-moshi:bintrayUpload
